version: '2'

services:
### Service: NodeJS Container ##########################
  api:
    build: ./api
    container_name: api
    tty: true
    volumes:
      - "./api:/api"
    ports:
      - "5000:5000"
    depends_on:
     - mysql
    command: "sh -c 'cd api ; npm run start'"
    env_file: ./api/.dev-env
    environment:
      - DOCKER=1
      - MYSQL_HOST=mysql
      - REDIS_ADDR=redis
      - REDIS_PORT=6379
    networks:
      - back

### Service: MySQL Container ##########################
  mysql:
    build: ./database/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    env_file: .dev-mysql-env
    environment:
      - MYSQL_HOST=0.0.0.0
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./database/mysql/dump:/docker-entrypoint-initdb.d
    networks:
      - back

### Service: Redis Key/Value ##########################
  redis:
    image: 'redis:3.0-alpine'
    container_name: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    networks:
      - back

### Network: Back (shared by mysql && api) ##########################
networks:
  back:
    driver: bridge
